server:
  port: 8080
#  servlet:
#    context-path: /bootdo
# 过时
security:
  base:
    enabled: false
spring:
  thymeleaf:
    cache: false        # 禁用缓存
    mode: LEGACYHTML5   # 非严谨型检查 默认是html 严格检查
  profiles:
    active:
      - dev

mybatis:
  mapper-locations:       # 指定mybatis配置sql路径
    - mybatis/**/*Dao.xml
  type-aliases-package: com.bootdo    #mybatis包
  configuration:
    mapUnderscoreToCamelCase: true    # 自动转驼峰

logging:
  config: classpath:logback-spring.xml
  level:
    com.bootdo: debug